// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Accent color configuration.
 */
export type AccentColor = { 
/**
 * Preset name: "ltk" (the brand accent), or one of the generated hues
 * "blue", "purple", "green", "orange", "pink", "red", "teal". `None` is
 * read as "ltk" by the frontend.
 */
preset: string | null, 
/**
 * Custom hue value (0-360) for custom colors
 */
customHue: number | null, };
