// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderFailure } from "./FolderFailure";
import type { WorkshopProject } from "./WorkshopProject";

/**
 * What adding a folder of mods did with each one.
 */
export type AddFoldersReport = { added: Array<WorkshopProject>, failed: Array<FolderFailure>, };
