// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextureInfo } from "./TextureInfo";
import type { WorkshopFileKind } from "./WorkshopFileKind";

/**
 * What an asset holds, for a viewer that reports it beside the preview.
 */
export type AssetInfo = { "kind": "texture" } & TextureInfo | { "kind": "image", width: number, height: number, sizeBytes: bigint, } | { "kind": "unsupported", fileKind: WorkshopFileKind, };
