// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a previewed asset's bytes come from.
 *
 * A reference crosses IPC from the webview, so every path in one is untrusted.
 * [`read`](Self::read) checks a relative path against the root it belongs to
 * rather than joining it on, and [`File`](Self::File) is the one variant that
 * names a path outright.
 */
export type AssetRef = { "kind": "layer", 
/**
 * The project directory.
 */
project: string, layer: string, 
/**
 * Path relative to the layer root, with forward slashes.
 */
path: string, } | { "kind": "gameChunk", 
/**
 * A `DATA/FINAL`-relative archive name.
 */
wad: string, 
/**
 * The chunk's path hash as 16 lowercase hex digits.
 */
pathHash: string, } | { "kind": "file", path: string, };
