// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The rule of section 10.2 that picked a base texture, in the order they are tried.
 */
export type BaseRule = "switchOverride" | "exact" | "colorMapOverPlaceholder" | "exactPlaceholder" | "nameLike" | "colorMapPath" | "colorMapPathAnyName";
