// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseRule } from "./BaseRule";
import type { NamedAsset } from "./NamedAsset";
import type { Wrap } from "./Wrap";

/**
 * The texture a preview draws a material's main layer with.
 */
export type BaseTexture = { 
/**
 * The shader texture's name, which the sampler entry is keyed by.
 */
name: string, texture: NamedAsset, 
/**
 * Which rule picked it, from surest to a last resort.
 */
rule: BaseRule, 
/**
 * The sampler's address modes, across and down.
 */
wrap: [Wrap, Wrap], };
