// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a suspect is one, as the line under its name.
 */
export type Because = "holds-the-path" | "redirected" | "rejected" | "did-not-verify" | "skipped" | "could-not-mount" | "unknown";
