// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Patcher binary identity
 */
export type BinaryId = { 
/**
 * 16 hex sha-256
 */
hash: string, built: number | null, };
