// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyEdit } from "./DependencyEdit";
import type { LeafValue } from "./LeafValue";
import type { ModuleAction } from "./ModuleAction";
import type { NewItem } from "./NewItem";
import type { NewProperty } from "./NewProperty";
import type { ObjectEdit } from "./ObjectEdit";
import type { ValueEdit } from "./ValueEdit";

/**
 * One edit of an open document, one variant per store method.
 *
 * `entry` is an object's hash as `0x` and eight hex digits, and `path` the wire form of a
 * property path (ADR-0027), empty for the object itself.
 */
export type BinEdit = { "kind": "patch", entry: string, path: string, value: LeafValue, } | { "kind": "editProperty", entry: string, holder: string, field: string, edits: Array<ValueEdit>, } | { "kind": "addProperty", entry: string, path: string, property: NewProperty, } | { "kind": "removeProperty", entry: string, path: string, } | { "kind": "insertItem", entry: string, path: string, item: NewItem, } | { "kind": "removeItem", entry: string, path: string, } | { "kind": "moveItem", entry: string, path: string, to: number, } | { "kind": "setKey", entry: string, path: string, key: string, } | { "kind": "setPointer", entry: string, path: string, className: string | null, } | { "kind": "declareReference", entry: string, path: string, reference: string, merge: boolean, } | { "kind": "object", edit: ObjectEdit, } | { "kind": "dependency", edit: DependencyEdit, } | { "kind": "moduleAction", layer: string, action: ModuleAction, };
