// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinFileKind } from "./BinFileKind";
import type { Dependency } from "./Dependency";
import type { ObjectName } from "./ObjectName";

/**
 * What the header row says about an open bin.
 */
export type BinHeader = { kind: BinFileKind, 
/**
 * The file version of a `PROP`. A `PTCH` carries none.
 */
version: number | null, 
/**
 * The objects the file declares. For a `PTCH`, the objects it adds.
 */
objects: number, dependencies: Array<Dependency>, 
/**
 * The patch records of a `PTCH`.
 */
patches: number, 
/**
 * The objects a `PTCH` deletes, in file order.
 */
deleted: Array<ObjectName>, };
