// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A read of what an add line of an open document offers.
 */
export type ChoiceQuery = { "kind": "addableFields", entry: string, path: string, } | { "kind": "objectClasses" } | { "kind": "itemClasses", entry: string, path: string, };
