// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddableFields } from "./AddableFields";
import type { ClassChoice } from "./ClassChoice";

/**
 * The answer to a [`ChoiceQuery`].
 */
export type Choices = { "kind": "fields", fields: AddableFields, } | { "kind": "classes", classes: Array<ClassChoice>, };
