// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldSchema } from "./FieldSchema";

/**
 * One class as the class card draws it: its name, and its fields typed at one build.
 */
export type ClassSchema = { 
/**
 * The class as the database names it.
 */
name: string | null, 
/**
 * The content build `declared` is read at: the install's, or the newest the
 * database names where the install has none it describes.
 */
build: number, 
/**
 * The patch a player names, where the install's own build is what was read.
 *
 * Absent where the database describes no build the install has and the newest it
 * names stood in, because that build belongs to no patch this install knows.
 */
patch: string | null, 
/**
 * The named fields first, by name, and the unnamed after them by hash.
 */
fields: Array<FieldSchema>, };
