// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Doc } from "./Doc";
import type { PropertyDocs } from "./PropertyDocs";

/**
 * The wiki's prose for one class and for the properties it and its bases declare.
 */
export type ClassDocs = { 
/**
 * The class's own prose. Absent where the wiki documents only properties.
 */
class: Doc | null, 
/**
 * Keyed by the property's hash, `0x` and eight hex digits.
 */
properties: { [key in string]: PropertyDocs }, };
