// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One code the log carried, with where and when.
 */
export type CodeSighting = { code: string, 
/**
 * Seconds into the log.
 */
at: number, 
/**
 * The whole record, redacted.
 */
line: string, };
