// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How sure the manager is. The evidence mark of the code sets the ceiling.
 */
export type Confidence = "lead" | "likely" | "confirmed";
