// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a verdict cost the player, which is a fact whatever the manager makes
 * of the line that reported it.
 *
 * The axis that replaced a confidence word. How firmly a log code can be read
 * is a claim about the manager's own table and belongs to the sentence that
 * reads the code, not stamped over what happened to the game.
 *
 * Ordered by how much the game lost, worst last.
 */
export type Consequence = "archive-dropped" | "overlay-off" | "game-hung" | "game-stopped";
