// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentObject } from "./ContentObject";
import type { IgnoreMatch } from "./IgnoreMatch";
import type { WorkshopFileKind } from "./WorkshopFileKind";

/**
 * A single file entry in a layer's content directory.
 */
export type ContentEntry = { 
/**
 * Path relative to the layer root, always POSIX-style (`/`).
 */
relativePath: string, sizeBytes: bigint, kind: WorkshopFileKind, 
/**
 * The objects a `.bin` declares, and empty for any other file.
 */
objects: Array<ContentObject>, 
/**
 * What leaves the file out of a package, null for one that ships.
 */
ignoredBy: IgnoreMatch | null, };
