// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a converted folder's project lives.
 */
export type ConvertPlacement = "inPlace" | "copy";
