// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConvertPlacement } from "./ConvertPlacement";

/**
 * Arguments for turning a folder into a project.
 */
export type ConvertFolderArgs = { path: string, name: string, displayName: string, placement: ConvertPlacement, };
