// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One module of the chosen layer's manifest.
 */
export type DeclaredModuleSummary = { 
/**
 * The module's index in `modules`.
 */
index: number, name: string | null, 
/**
 * An `entries` module, which takes new keys. A `target` module does not.
 */
takesKeys: boolean, };
