// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a declared document takes edits, the project's "Use game data declarations".
 *
 * Off draws the same applied tree and marks, read-only.
 */
export type Declaring = "on" | "off";
