// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectChange } from "./ObjectChange";

/**
 * What a declaration of the chosen layer does to one object of the chunk.
 */
export type DeclaredObjectMark = { 
/**
 * The object's path hash, `0x` and eight hex digits.
 */
entry: string, change: ObjectChange, };
