// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredDiagnosticKind } from "./DeclaredDiagnosticKind";
import type { ObjectSkip } from "./ObjectSkip";
import type { SkipReason } from "./SkipReason";

/**
 * One diagnostic of the last apply, on the row it names.
 */
export type DeclaredDiagnostic = { 
/**
 * The object's path hash, `0x` and eight hex digits. Empty where the diagnostic names no
 * object of the chunk.
 */
entry: string, 
/**
 * The row's path on the wire. Empty where the key reaches no row, which lists the
 * diagnostic under its object.
 */
path: string, 
/**
 * The layer whose declaration raised it.
 */
layer: string, 
/**
 * The signed key, the link path or the override path the diagnostic is about.
 */
key: string, kind: DeclaredDiagnosticKind, 
/**
 * Why a property edit was skipped. Absent for every other kind.
 */
reason: SkipReason | null, 
/**
 * Why an object's creation or removal was skipped. Absent for every other kind.
 */
object: ObjectSkip | null, 
/**
 * What a lower layer said, where it said something the codes do not carry.
 */
detail: string | null, };
