// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkChange } from "./LinkChange";

/**
 * What a declaration of the chosen layer does to one dependency of the chunk.
 */
export type DeclaredLinkMark = { 
/**
 * The dependency as the applied list spells it, or the game's list for a removal.
 */
path: string, change: LinkChange, };
