// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredSign } from "./DeclaredSign";
import type { LineSpan } from "./LineSpan";

/**
 * One signed property key of an entry body.
 */
export type DeclaredKey = { 
/**
 * The key as the build reads it, sign included.
 */
key: string, sign: DeclaredSign, 
/**
 * The property path, without the sign.
 */
path: string, 
/**
 * The value as YAML text: the manifest's own spelling where it is in the manifest.
 */
value: string, 
/**
 * The wire path of the row the key reaches, cut before the first map key, which only
 * the bin itself can spell.
 */
row: string, 
/**
 * From the key to the end of its value.
 */
span: LineSpan | null, };
