// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredDiagnostic } from "./DeclaredDiagnostic";
import type { DeclaredLinkMark } from "./DeclaredLinkMark";
import type { DeclaredMark } from "./DeclaredMark";
import type { DeclaredModuleChoice } from "./DeclaredModuleChoice";
import type { DeclaredModuleSummary } from "./DeclaredModuleSummary";
import type { DeclaredObjectMark } from "./DeclaredObjectMark";

/**
 * What a declared document says beside its rows.
 */
export type DeclaredState = { 
/**
 * The layer an edit writes to.
 */
layer: string, 
/**
 * The module of `layer` a new key joins.
 */
module: DeclaredModuleChoice, 
/**
 * The modules of `layer` in execution order.
 */
modules: Array<DeclaredModuleSummary>, 
/**
 * The project's layers in build order.
 */
layers: Array<string>, 
/**
 * The rows a declaration of `layer` touches.
 */
marks: Array<DeclaredMark>, 
/**
 * The objects a declaration of `layer` creates or removes.
 */
objects: Array<DeclaredObjectMark>, 
/**
 * The dependencies a declaration of `layer` adds or removes.
 */
links: Array<DeclaredLinkMark>, 
/**
 * What the last apply reported, over every layer.
 */
diagnostics: Array<DeclaredDiagnostic>, };
