// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The module a declared document's new keys join. ADR-0048.
 */
export type DeclaredModuleChoice = { "kind": "auto" } | { "kind": "index", index: number, } | { "kind": "new", name: string | null, };
