// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The category of a [`DeclaredDiagnostic`], as `ltk_game_data` names it.
 */
export type DeclaredDiagnosticKind = "overrideUnreadable" | "overrideInvalid" | "overrideRecordSkipped" | "linkRemovalUnmatched" | "propertyEditSkipped" | "schemaFallback" | "referenceUnreadable" | "objectSkipped" | "unknown";
