// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineSpan } from "./LineSpan";

/**
 * Why a layer's declarations do not load, and where.
 */
export type DeclarationsLoadError = { message: string, 
/**
 * The file the error is in, as the loader names it: the manifest's name or a source path.
 */
document: string | null, 
/**
 * Where in the manifest, `None` for an error in another file or at no place.
 */
span: LineSpan | null, };
