// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclarationsLoadError } from "./DeclarationsLoadError";
import type { DeclaredModule } from "./DeclaredModule";

/**
 * One layer's declarations manifest, read for an outline.
 */
export type DeclarationsLayer = { layer: string, 
/**
 * The manifest's path inside the layer, `None` for a layer with none.
 */
file: string | null, 
/**
 * The manifest's text with `\r\n` read as `\n`, which every span indexes.
 */
text: string | null, 
/**
 * Why the declarations do not load. `modules` is empty beside one.
 */
error: DeclarationsLoadError | null, 
/**
 * The modules in execution order.
 */
modules: Array<DeclaredModule>, };
