// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One patcher binary as a decoded token presents it: the checksum, and the
 * build date as a full timestamp.
 */
export type DecodedBinary = { hash: string, 
/**
 * RFC 3339, UTC, when the build date was a date.
 */
built: string | null, };
