// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Consequence } from "./Consequence";
import type { DecodedBinary } from "./DecodedBinary";
import type { Ending } from "./Ending";
import type { EvidenceCode } from "./EvidenceCode";
import type { GamePhase } from "./GamePhase";
import type { LaunchKind } from "./LaunchKind";
import type { OriginKind } from "./OriginKind";
import type { OverlayOutcome } from "./OverlayOutcome";
import type { ScanMode } from "./ScanMode";
import type { ScanStatus } from "./ScanStatus";
import type { SkippedArchive } from "./SkippedArchive";
import type { VerdictKind } from "./VerdictKind";

/**
 * A token read against this build's tables, for a reader.
 *
 * Each enum is `None` for a number this build does not know, with the
 * verdict's number kept beside it, so a token from a newer manager reads as
 * far as it can and never as an error.
 */
export type DecodedIncident = { 
/**
 * RFC 3339, UTC, to the minute, or `None` when the token carried no time.
 */
endedAt: string | null, 
/**
 * `1.14.0`.
 */
manager: string, 
/**
 * `16.16.804.9184`.
 */
game: string | null, verdict: VerdictKind | null, 
/**
 * The verdict's number as the token carries it, for one this build does
 * not know.
 */
verdictCode: number, 
/**
 * The verdict's title, or `Verdict 17` for one this build does not know.
 */
title: string, consequence: Consequence | null, origin: OriginKind | null, overlay: OverlayOutcome | null, scan: ScanMode | null, launch: LaunchKind | null, injected: boolean, hostElevated: boolean, phase: GamePhase | null, ending: Ending, durationSecs: number | null, 
/**
 * Each code with what this build's table says about it.
 */
codes: Array<EvidenceCode>, lastLoadStep: number | null, missingHash: string | null, subject: string | null, suspects: Array<string>, skipped: Array<SkippedArchive>, redirectedCount: number, enabledCount: number, 
/**
 * The hook DLL that ran, with its build date read out.
 */
dll: DecodedBinary | null, 
/**
 * The injection host that ran.
 */
host: DecodedBinary | null, 
/**
 * Whether both binaries are the ones the sender's manager build shipped.
 */
patcherOk: boolean | null, scanStatus: ScanStatus | null, 
/**
 * The status code as the scan reported it, beside the reading.
 */
scanStatusCode: string | null, failure: string | null, overlayDetail: string | null, };
