// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One dependency a `PROP` names, as its path and its brex spelling.
 */
export type Dependency = { 
/**
 * The archive path as the file writes it.
 */
path: string, 
/**
 * The path in brex, which folds the repeated terms of a packed bin name. Absent where
 * the path repeats nothing.
 */
packed: string | null, };
