// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An edit of the header's dependency list. ADR-0050.
 */
export type DependencyEdit = { "kind": "insert", index: number | null, text: string, } | { "kind": "remove", index: number, } | { "kind": "move", from: number, to: number, } | { "kind": "set", index: number, text: string, } | { "kind": "restore", path: string, };
