// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the wiki writes about one class or one property, each part markdown.
 */
export type Doc = { 
/**
 * The body. Absent where the entry carries notes or examples alone.
 */
description: string | null, 
/**
 * Short caveats, one paragraph each.
 */
notes: Array<string>, 
/**
 * Worked examples, one block each.
 */
examples: Array<string>, };
