// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PropertyKind } from "./PropertyKind";

/**
 * Why a leaf edit's value does not fit the node it addresses.
 */
export type EditRejection = { "reason": "notALeaf" } | { "reason": "wrongKind", kind: PropertyKind, } | { "reason": "outOfRange", kind: PropertyKind, } | { "reason": "notFinite" } | { "reason": "wrongLength", expected: number, } | { "reason": "malformedHash" } | { "reason": "notAHolder" } | { "reason": "notAProperty" } | { "reason": "propertyExists" } | { "reason": "undeclaredField" } | { "reason": "missingClass" } | { "reason": "invalidShape" } | { "reason": "notAList" } | { "reason": "notAnItem" } | { "reason": "notAPointer" } | { "reason": "keyExists" } | { "reason": "missingKey" } | { "reason": "valueHeld" } | { "reason": "noSuchIndex" } | { "reason": "emptyPath" } | { "reason": "malformedBrex" } | { "reason": "dependencyExists" } | { "reason": "namelessPath" } | { "reason": "undeclarable" } | { "reason": "untypable" } | { "reason": "objectExists" };
