// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredState } from "./DeclaredState";
import type { LeafValue } from "./LeafValue";

/**
 * What a landed [`BinEdit`] answers beside the change itself.
 */
export type EditOutcome = { "kind": "done" } | { "kind": "previous", value: LeafValue, } | { "kind": "object", entry: string, } | { "kind": "path", path: string, } | { "kind": "index", index: number, } | { "kind": "declared", state: DeclaredState, };
