// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the game ended, as far as anything said.
 */
export type Ending = { 
/**
 * The Riot Client's reason: `Exit`, `Interrupt`, `Timeout`, `Unknown`, or a
 * spelling the crate does not know. `None` on the Classic launch flow.
 */
exitReason: string | null, exitCode: number | null, 
/**
 * Whether `last_crash` fell inside the game's window. `None` when the
 * marker was not read.
 */
crashed: boolean | null, };
