// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error codes that can be communicated across the IPC boundary.
 * These are serialized as SCREAMING_SNAKE_CASE for TypeScript consumption.
 */
export type ErrorCode = "IO" | "SERIALIZATION" | "MODPKG" | "LEAGUE_NOT_FOUND" | "INVALID_PATH" | "MOD_NOT_FOUND" | "VALIDATION_FAILED" | "INTERNAL_STATE" | "MUTEX_LOCK_FAILED" | "UNKNOWN" | "WORKSHOP_NOT_CONFIGURED" | "PROJECT_NOT_FOUND" | "PROJECT_ALREADY_EXISTS" | "PACK_FAILED" | "FANTOME" | "WAD" | "PATCHER" | "ZIP" | "SCHEMA_VERSION_TOO_NEW" | "WORKSHOP" | "RIOT_CLIENT_NOT_FOUND" | "RIOT_CLIENT_UNREACHABLE" | "LAUNCH_REFUSED" | "LAUNCH_FAILED" | "HASHTABLE_CACHE_DIR_UNAVAILABLE" | "HASHTABLE_MANIFEST_INVALID" | "HASHTABLE_SYNC_LOCKED" | "HASHTABLE_SYNC_FAILED" | "PREVIEW";
