// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceCode } from "./EvidenceCode";
import type { EvidenceSource } from "./EvidenceSource";

/**
 * One line the verdict rests on.
 */
export type Evidence = { 
/**
 * Seconds into the game where the source has one, else the wall clock.
 */
at: string, source: EvidenceSource, line: string, code: EvidenceCode | null, };
