// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How firm a row's reading is. The confidence ceiling of any verdict on it.
 */
export type EvidenceMark = "confirmed" | "inferred";
