// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How firm a row's reading is, which is a claim about this table and no more.
 *
 * It hedges the one sentence that reads the code and nothing else. What a
 * verdict cost the game is a fact the manager observed, so the mark never
 * grades it - see [`Consequence`](super::incident::Consequence).
 */
export type EvidenceMark = "confirmed" | "inferred";
