// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EvidenceMark } from "./EvidenceMark";

/**
 * What the table says about a code on an evidence line.
 */
export type EvidenceCode = { id: string, 
/**
 * The kind column, or `None` when the table has no row.
 */
kind: string | null, meaning: string | null, mark: EvidenceMark | null, };
