// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a line of evidence came from.
 */
export type EvidenceSource = "patcher" | "host" | "dll" | "game" | "client";
