// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractKindCount } from "./ExtractKindCount";

/**
 * What an extract did, summed over every archive it read.
 */
export type ExtractSummary = { extracted: number, skippedExisting: number, skippedByFilter: number, 
/**
 * Chunks the index named that the archive turned out not to hold, which
 * means the two disagree rather than that anything failed.
 */
missing: number, bytesWritten: bigint, 
/**
 * Written files by the kind their bytes identify as, most first.
 */
byKind: Array<ExtractKindCount>, 
/**
 * The cancel flag was set, so this is a part of what was asked for.
 */
cancelled: boolean, 
/**
 * Names the archives' own bins gave chunks no hash table knew.
 */
recovered: number, 
/**
 * Chunks written under a name their resolved path did not give, because a
 * directory held that name or another chunk claimed it first.
 */
renamed: number, 
/**
 * Chunks whose resolved path the extraction refused to write, so nothing
 * landed for them. A hash table naming a path that escapes the output
 * directory is the usual cause.
 */
rejected: number, 
/**
 * Chunks another chunk's path claimed first that went unwritten. Zero
 * under a lossless naming policy, which renames them instead.
 */
duplicates: number, 
/**
 * The folder written into, for the report's **Open folder**.
 */
destination: string, };
