// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderWad } from "./FolderWad";

/**
 * A fantome-layout folder, as the conversion would read it.
 */
export type FantomeFolder = { displayName: string, suggestedName: string, author: string | null, version: string | null, 
/**
 * Whether `META/info.json` was there to read the metadata from.
 */
hasInfo: boolean, wads: Array<FolderWad>, 
/**
 * Whether a `RAW/` directory holds loose files.
 */
hasRaw: boolean, };
