// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one fix run did to a file, as against how much of it.
 *
 * The counts beside this say how much a rule changed. This says whether the
 * file survived, which is what an archive edit has to know before it can state
 * the repair as a chunk write.
 */
export type FileChange = "written" | "removed";
