// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";

/**
 * What one fix run did to one file.
 */
export type FileOutcome = { layer: string, 
/**
 * POSIX-style and relative to the layer root.
 */
path: string, applied: number, skipped: number, 
/**
 * Whether the file is still there.
 *
 * Defaulted for a report recorded before a repair could delete anything,
 * which is every report written before this field existed.
 */
change: FileChange, };
