// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileOutcome } from "./FileOutcome";

/**
 * What one fix run applied, skipped and wrote.
 */
export type FixReport = { 
/**
 * The restore point this run wrote, which Undo names.
 */
stamp: string, applied: number, 
/**
 * Problems the file no longer matched, which the rules left alone.
 */
skipped: number, 
/**
 * Paths this run wrote into the mod's own tables before hashing them.
 */
namesKept: number, files: Array<FileOutcome>, 
/**
 * A file a rule could not finish, and why.
 */
failed: Array<string>, };
