// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileOutcome } from "./FileOutcome";
import type { ProblemId } from "./ProblemId";

/**
 * What one fix run applied, skipped and wrote.
 */
export type FixReport = { applied: number, 
/**
 * Problems the file no longer matched, which the rules left alone.
 */
skipped: number, 
/**
 * Paths this run wrote into the mod's own tables before hashing them.
 */
namesKept: number, 
/**
 * The migration tables the run applied.
 */
tables: Array<string>, 
/**
 * The named problems a re-check still saw once the run had written.
 *
 * Read off the repaired tree in memory rather than by analyzing the
 * project a second time. Empty is the ordinary outcome.
 */
remaining: Array<ProblemId>, files: Array<FileOutcome>, 
/**
 * A file a rule could not finish, and why.
 */
failed: Array<string>, };
