// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A folder the batch could not add, and why.
 */
export type FolderFailure = { path: string, message: string, };
