// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FantomeFolder } from "./FantomeFolder";
import type { WorkshopProject } from "./WorkshopProject";

/**
 * What a folder picked with Open folder holds.
 */
export type FolderInspection = { "kind": "missing" } | { "kind": "project", project: WorkshopProject, } | { "kind": "fantome", layout: FantomeFolder, } | { "kind": "parent", projects: Array<string>, fantome: Array<string>, } | { "kind": "plain", suggestedName: string, displayName: string, };
