// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of a fantome folder's `WAD/` directory.
 */
export type FolderWad = { name: string, 
/**
 * A packed archive, which the conversion unpacks, rather than a directory it moves.
 */
packed: boolean, };
