// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far the game got, as its log says.
 */
export type GamePhase = "unknown" | "loading" | "in-game" | "torn-down";
