// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One WAD archive in a game install.
 */
export type GameWadSummary = { 
/**
 * Path relative to `DATA/FINAL` with forward slashes, e.g.
 * `Champions/Aatrox.wad.client`.
 */
name: string, 
/**
 * Archive file size on disk, or 0 when it cannot be read.
 */
sizeBytes: bigint, };
