// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One chunk of a WAD archive.
 */
export type GameWadEntry = { 
/**
 * Chunk path hash as 16 lowercase hex digits.
 */
pathHash: string, 
/**
 * Resolved chunk path, or `None` when no hashtable knows the hash.
 */
path: string | null, 
/**
 * Uncompressed chunk size.
 */
sizeBytes: bigint, };
