// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file of the folded index, in the shape a single archive reads back.
 */
export type GameFileEntry = { 
/**
 * Chunk path hash as 16 lowercase hex digits.
 */
pathHash: string, 
/**
 * Resolved chunk path, or `None` when no hash table names it.
 */
path: string | null, 
/**
 * Uncompressed chunk size.
 */
sizeBytes: bigint, };
