// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for the `patcher-game-attached` event: the DLL is in the game,
 * which says nothing yet about whether the overlay went live.
 */
export type GameAttachedPayload = { 
/**
 * The game's process id, when a `dll` line named it.
 */
pid: number | null, };
