// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlayOutcome } from "./OverlayOutcome";

/**
 * Payload for the `patcher-game-overlay` event: what the DLL said about the
 * overlay after it attached.
 */
export type GameOverlayPayload = { outcome: OverlayOutcome, };
