// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One subdirectory, folded through any chain of single-child directories.
 */
export type GameDirEntry = { 
/**
 * What [`GameIndex::read_dir`] takes to open this row, forward slashes.
 */
path: string, 
/**
 * What the row reads: the folded chain of segments joined by `/`.
 */
name: string, 
/**
 * Files at or below the directory.
 */
fileCount: number, };
