// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The facts the game log gives about the game itself.
 */
export type GameInfo = { version: string, contentVersion: string, logPath: string, };
