// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a built index holds.
 */
export type GameIndexStats = { 
/**
 * Archives merged, including any that failed to read.
 */
archives: number, 
/**
 * Files after deduplication.
 */
files: number, 
/**
 * Directories, not counting the root.
 */
dirs: number, };
