// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameDirEntry } from "./GameDirEntry";
import type { GameFileEntry } from "./GameFileEntry";

/**
 * What one directory of the folded index holds.
 */
export type GameDirListing = { 
/**
 * Subdirectories, sorted by name.
 */
dirs: Array<GameDirEntry>, 
/**
 * Files directly under this directory, sorted by name.
 */
files: Array<GameFileEntry>, };
