// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HashtableUpdate } from "./HashtableUpdate";
import type { MetaSchemaVersion } from "./MetaSchemaVersion";

/**
 * What a sync would install, asked without installing anything.
 */
export type HashtableUpdateCheck = { 
/**
 * True when a sync would install nothing.
 */
upToDate: boolean, 
/**
 * The tables a sync would download, in manifest order.
 */
behind: Array<HashtableUpdate>, 
/**
 * How many bytes those add up to, absent against a release that recorded
 * no sizes.
 */
downloadBytes: bigint | null, 
/**
 * Remote table ids this build does not know. A sync skips them.
 */
unknownTables: Array<string>, 
/**
 * Ids published in a `.hashdb` format this build cannot open. Named apart
 * from [`behind`](Self::behind) because syncing cannot install them, so
 * counting them as pending updates would promise a fix that is not there.
 */
unsupportedTables: Array<string>, 
/**
 * The meta schema database that is published, when it is not the cached
 * one.
 *
 * Apart from [`behind`](Self::behind), which is tables and is drawn
 * against them, but counted in [`up_to_date`](Self::up_to_date) because
 * one sync covers both.
 */
schemaBehind?: MetaSchemaVersion, };
