// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HashtableStatus } from "./HashtableStatus";

/**
 * What the shared hashtable cache currently holds.
 */
export type HashtableCacheStatus = { 
/**
 * Absolute cache directory.
 */
dir: string, 
/**
 * Manifest generation time (RFC 3339), or `None` when the cache is empty.
 */
generatedAt: string | null, 
/**
 * Repository the table inputs came from, e.g. `CommunityDragon/Data`.
 */
sourceRepo: string | null, 
/**
 * Commit of that repository the inputs were taken at.
 */
sourceCommit: string | null, 
/**
 * Present tables, in [`Table::ALL`] order.
 */
tables: Array<HashtableStatus>, 
/**
 * Ids from [`Table::ALL`] absent from the manifest.
 */
missing: Array<string>, };
