// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of a hashtable sync, one event per release asset download.
 */
export type HashtableSyncProgress = { 
/**
 * Release asset filename being fetched, e.g. `manifest.json`.
 */
file: string, };
