// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HashtableStatus } from "./HashtableStatus";
import type { MetaSchemaVersion } from "./MetaSchemaVersion";

/**
 * What the shared hashtable cache currently holds.
 */
export type HashtableCacheStatus = { 
/**
 * Absolute cache directory.
 */
dir: string, 
/**
 * Manifest generation time (RFC 3339), or `None` when the cache is empty.
 */
generatedAt: string | null, 
/**
 * Present tables, in [`Table::ALL`] order.
 */
tables: Array<HashtableStatus>, 
/**
 * Ids from [`Table::ALL`] absent from the manifest.
 */
missing: Array<string>, 
/**
 * The meta schema database a check would read.
 *
 * The cached copy where a sync has installed one, and the snapshot this
 * build ships otherwise, so it is never absent.
 */
schema: MetaSchemaVersion, };
