// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One present table in a [`HashtableCacheStatus`].
 */
export type HashtableStatus = { 
/**
 * Stable table id, e.g. `game`.
 */
id: string, 
/**
 * Active `.lhdb` filename from the manifest.
 */
file: string, 
/**
 * Entry count recorded in the manifest.
 */
entries: bigint, 
/**
 * On-disk size of the active file, or 0 when it cannot be read.
 */
sizeBytes: bigint, };
