// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a check ran against, and therefore what makes an old one stale.
 *
 * Per "The basis" in docs/ux/MOD_HEALTH.md.
 */
export type HealthCheckBasis = { 
/**
 * The installed game build, absent where none could be read.
 */
build: string | null, 
/**
 * The manager version, which is what a migration table ships in.
 */
manager: string, 
/**
 * What the shared hashtable cache held, absent where it held nothing.
 *
 * The cache's own generation stamp, which moves only when a sync installs
 * a table. A check taken against different tables was a claim about
 * different names, so a sync makes every verdict due again without waiting
 * for a game patch.
 */
tables?: string, 
/**
 * What the meta schema database held, absent where none was open.
 *
 * It decides `bin/property-type` outright, so a check taken against
 * another database was a claim about other types. The database's own bytes
 * rather than the stamp it carries, because the publisher restamps the
 * hash tables behind it on a schedule of its own - a database that has
 * gained two patches can still carry the stamp it was first published
 * under.
 */
schema?: string, };
