// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a check ran against, and therefore what makes an old one stale.
 *
 * Per "The basis" in docs/ux/MOD_HEALTH.md.
 */
export type HealthCheckBasis = { 
/**
 * The installed game build, absent where none could be read.
 */
build: string | null, 
/**
 * The manager version, which is what a migration table ships in.
 */
manager: string, };
