// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of a mod health sweep, emitted per mod.
 *
 * The mod is named by id rather than by title: the library view already holds
 * every mod's name, and looking one up here would mean a `mod.config.json`
 * read per mod on top of the check itself.
 */
export type HealthSweepProgress = { current: number, total: number, modId: string, };
