// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModTiming } from "./ModTiming";

/**
 * What one timed pass over the library cost.
 */
export type HealthTiming = { 
/**
 * Whether the pass repaired, or only checked.
 */
repaired: boolean, 
/**
 * Wall-clock milliseconds for the whole pass, concurrency included.
 */
totalMs: bigint, 
/**
 * One row per mod, slowest first.
 */
mods: Array<ModTiming>, };
