// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthSweepReport } from "./HealthSweepReport";

/**
 * What the library sweep has to say for itself this launch.
 *
 * The run starts with the app and can be over before a webview exists to hear
 * it announced, so the outcome is kept for whoever asks next rather than only
 * emitted — the same reason
 * [`LayoutMigrationState`](crate::mods::LayoutMigrationState) is kept.
 */
export type HealthSweepState = { "status": "pending" } | { "status": "idle" } | { "status": "running", completed: number, total: number, } | { "status": "finished", report: HealthSweepReport, };
