// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `.modignore` line that keeps an entry out of a package.
 */
export type IgnoreMatch = { 
/**
 * The pattern as written, its trailing `/` included.
 */
pattern: string, 
/**
 * The `.modignore` holding the pattern, relative to the project.
 */
source: string, 
/**
 * One-based line of the pattern, null where it cannot be recovered.
 */
line: number | null, };
