// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A project's root ignore rules, as the editor reads them.
 */
export type IgnoreRules = { 
/**
 * Absolute path of the project's `.modignore`, whether or not one exists.
 */
path: string, 
/**
 * The file's text, null when the project has no file.
 */
text: string | null, 
/**
 * Recommended patterns the file lacks, in the order the default lists them.
 */
missingRecommended: Array<string>, };
