// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `.modignore` of a project, as the editor reads it.
 */
export type IgnoreRules = { 
/**
 * Absolute path of the file, whether or not one exists.
 */
path: string, 
/**
 * The file's text, null when the file does not exist.
 */
text: string | null, 
/**
 * Recommended patterns the file lacks, in the order the default lists them.
 *
 * Empty for anything but the root file, whose anchor the default assumes.
 */
missingRecommended: Array<string>, };
