// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IgnoreMatch } from "./IgnoreMatch";

/**
 * A directory the rules leave out, along with everything under it.
 */
export type IgnoredDirectory = { 
/**
 * Path relative to the layer root, always POSIX-style (`/`).
 */
relativePath: string, ignoredBy: IgnoreMatch, };
