// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An entry the ignore rules kept out of a package.
 */
export type IgnoredEntry = { 
/**
 * Path under `content/`, forward-slashed, where a rule's own path starts.
 */
path: string, 
/**
 * A pruned directory, which stands for everything under it.
 */
directory: boolean, };
