// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The incident, as the token carries it. Names and paths on disk stay out.
 */
export type IncidentToken = { 
/**
 * Minutes since the Unix epoch.
 */
endedAt: number, manager: [number, number, number], game: [number, number, number, number] | null, verdict: number, confidence: number | null, overlay: number, scan: number | null, launch: number, injected: boolean, exitReason: string | null, exitCode: number | null, crashed: boolean | null, durationSecs: number | null, 
/**
 * The codes seen, as their own strings, so a token reads against any
 * version of the table.
 */
codes: Array<string>, lastLoadStep: number | null, 
/**
 * The missing-data hash, as sixteen hex digits.
 */
missingHash: string | null, 
/**
 * Archive names, and the suspects' display names cut to 32 characters.
 */
archives: Array<string>, suspects: Array<string>, skipped: Array<string>, redirectedCount: number, enabledCount: number, errorLines: number, hostFailure: string | null, };
