// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ending } from "./Ending";
import type { Evidence } from "./Evidence";
import type { GameInfo } from "./GameInfo";
import type { LaunchKind } from "./LaunchKind";
import type { OverlayOutcome } from "./OverlayOutcome";
import type { ScanMode } from "./ScanMode";
import type { ScanStatus } from "./ScanStatus";
import type { SessionOrigin } from "./SessionOrigin";
import type { SkippedArchive } from "./SkippedArchive";
import type { Suspect } from "./Suspect";
import type { Verdict } from "./Verdict";

/**
 * The record the manager keeps for one game that went wrong.
 */
export type Incident = { 
/**
 * The game log's stamp, or the game's start when there is no log.
 */
id: string, 
/**
 * RFC 3339, UTC.
 */
startedAt: string, endedAt: string, 
/**
 * Library, or the workshop projects under test.
 */
origin: SessionOrigin, 
/**
 * Whether the DLL attached to this game.
 */
injected: boolean, overlay: OverlayOutcome, 
/**
 * The archives the DLL served from the overlay, by their last path segment.
 */
redirected: Array<string>, skipped: Array<SkippedArchive>, launch: LaunchKind, scan: ScanMode | null, 
/**
 * What the integrity scan reported, when it rejected an archive.
 */
scanStatus: ScanStatus | null, game: GameInfo | null, ending: Ending, verdict: Verdict, evidence: Array<Evidence>, suspects: Array<Suspect>, 
/**
 * The user has seen it and closed the line.
 */
dismissed: boolean, };
