// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarvestSummary } from "./HarvestSummary";
import type { ModArchiveFormat } from "./ModArchiveFormat";
import type { ModLayer } from "./ModLayer";
import type { ModLicense } from "./ModLicense";
import type { ModStorage } from "./ModStorage";

/**
 * A mod entry shown in the UI Library.
 */
export type InstalledMod = { id: string, name: string, displayName: string, version: string, description: string | null, authors: Array<string>, enabled: boolean, installedAt: string, layers: Array<ModLayer>, tags: Array<string>, champions: Array<string>, maps: Array<string>, 
/**
 * Directory where the mod is installed
 */
modDir: string, 
/**
 * The file this mod arrived as.
 */
format: ModArchiveFormat, 
/**
 * Where this mod's content is read from.
 */
storage: ModStorage, 
/**
 * Whether the archive is still beside the mod, which is what makes
 * [`storage`](Self::storage) switchable either way.
 */
hasArchive: boolean, 
/**
 * ID of the containing folder, or None if ungrouped.
 */
folderId: string | null, 
/**
 * What the mod's config declares it is licensed under, if it declares one.
 */
license?: ModLicense | null, 
/**
 * The mod's directory name under `mods/`.
 *
 * `None` while the mod is still in the legacy layout the migration has
 * not moved it out of.
 */
slug?: string | null, 
/**
 * What preserving the mod's names at import found. `None` for a modpkg
 * and for mods installed before the preserve existed.
 */
harvest?: HarvestSummary | null, };
