// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of game it was, as the DLL read the command line.
 */
export type LaunchKind = "match" | "replay" | "spectator" | "pbe";
