// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentEntry } from "./ContentEntry";
import type { IgnoredDirectory } from "./IgnoredDirectory";

/**
 * The files inside a single layer directory.
 */
export type LayerContent = { name: string, fileCount: number, totalSizeBytes: bigint, entries: Array<ContentEntry>, 
/**
 * The directories a rule leaves out, which no entry of its own names.
 */
ignoredDirectories: Array<IgnoredDirectory>, };
