// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModRepairFailure } from "./ModRepairFailure";

/**
 * What one repair over several mods became of each of them.
 */
export type LibraryRepairReport = { 
/**
 * Mods a repair wrote to, by id.
 */
repaired: Array<string>, 
/**
 * Mods the rules found nothing left to apply to, by id.
 */
unchanged: Array<string>, 
/**
 * Mods that could not be repaired, and why.
 */
failed: Array<ModRepairFailure>, 
/**
 * Findings repaired across every mod.
 */
applied: number, };
