// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A range of a text by one-based lines and one-based character columns, the end exclusive.
 */
export type LineSpan = { line: number, column: number, endLine: number, endColumn: number, };
