// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a declaration adds a dependency or removes one.
 */
export type LinkChange = "added" | "removed";
