// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One library mod whose property-bins reference linked dependencies no archive
 * the game mounts can answer.
 *
 * The lookup is across every mounted archive rather than inside the one the
 * declaring bin came from, so what the check tests is presence anywhere in the
 * built overlay bar the archives the user blocked.
 */
export type LinkedBinOffenderInfo = { 
/**
 * Library mod id (matches `InstalledMod.id` on the frontend).
 */
modId: string, 
/**
 * Mod display name — a fallback for the UI when it can't resolve the id.
 */
displayName: string, 
/**
 * WAD targets (e.g. `Ahri.wad.client`) in this mod that contain the unresolved
 * bins. May be empty when the offending bin came from a RAW override.
 */
wads: Array<string>, 
/**
 * The missing linked bin paths, deduped.
 */
missingLinks: Array<string>, };
