// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for the `linked-bins-warning` event, emitted after a patcher start whose
 * single overlay build found enabled mods with unresolved linked dependencies (only
 * when `linked_bin_check_enabled`). Injection is non-fatal, so this never blocks the
 * start — it drives a non-blocking toast. The per-mod badges and the reachable
 * `LinkedBinWarningDialog` carry the detail (fetched via `get_linked_bin_offenders`).
 */
export type LinkedBinWarningPayload = {
  /**
   * Number of enabled mods flagged in the latest build.
   */
  count: number;
};
