// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something the engine does silently that a preview says out loud.
 */
export type MaterialWarning = { "kind": "noShaderDefs" } | { "kind": "noPass" } | { "kind": "unresolvedShader", hash: string, } | { "kind": "secondPass" } | { "kind": "undeclaredSampler", name: string, } | { "kind": "undeclaredParam", name: string, } | { "kind": "undeclaredSwitch", name: string, } | { "kind": "stringTexturePath", name: string, path: string, } | { "kind": "textureNotFound", name: string, path: string, };
