// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseTexture } from "./BaseTexture";
import type { MaterialWarning } from "./MaterialWarning";
import type { RenderState } from "./RenderState";

/**
 * One `StaticMaterialDef` as a preview draws it, cut down to the slots one stock
 * material takes.
 */
export type MaterialPreview = { 
/**
 * The material's path hash, `0x` and eight hex digits.
 */
hash: string, 
/**
 * The material's path, where a table names it.
 */
name: string | null, 
/**
 * The document declares no object under the link, so every slot is empty and the
 * submesh draws as an error rather than as a guess.
 */
missing: boolean, 
/**
 * `dynamicMaterial` is set, so the slots are the static values of an animated
 * material.
 */
animated: boolean, 
/**
 * The pass shader's `objectPath`, and none where the link resolves to nothing.
 */
shader: string | null, 
/**
 * The texture the material's main layer samples, and none for a material with no
 * texture at all.
 */
base: BaseTexture | null, 
/**
 * A colour the base is multiplied by, in the shader's own units.
 */
tint: [number, number, number] | null, opacity: number | null, 
/**
 * The alpha a fragment is discarded below.
 */
alphaTest: number | null, 
/**
 * How many times the base tiles across the mesh.
 */
uvRepeat: [number, number] | null, 
/**
 * How far the base moves per second, in tiles.
 */
uvScroll: [number, number] | null, renderState: RenderState, 
/**
 * Every drop, miss and fallback the read made, in the order it made them.
 */
warnings: Array<MaterialWarning>, };
