// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one meta schema database is, as the cache card names it.
 *
 * The patch rather than the generation: the publisher restamps the hash tables
 * on their own schedule, so a database gains patches between two stamps.
 */
export type MetaSchemaVersion = { 
/**
 * The patch naming the newest build it describes, absent where it names none.
 */
patch: string | null, 
/**
 * That build, which is as far as the database reaches.
 */
build: number, 
/**
 * When the upstream hash tables behind it were read.
 */
generation: string, };
