// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of a mod's text documents, or why there is none to show.
 *
 * An absent document and a document that could not be read are two facts. The
 * second says the mod's archive is not answering, which is a mod that may not
 * work at all, and reporting it as a mod whose author wrote nothing is a
 * silent lie about something the reader has installed.
 */
export type ModDocument = { "state": "present", text: string, } | { "state": "absent" } | { "state": "unreadable", reason: string, };
