// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Counts } from "./Counts";
import type { HealthCheckBasis } from "./HealthCheckBasis";
import type { ModHealth } from "./ModHealth";

/**
 * What one check concluded, summarized for a mod user.
 */
export type ModHealthVerdict = { modId: string, health: ModHealth, 
/**
 * How many findings a repair would fix.
 */
fixable: number, 
/**
 * Every live finding by severity, fixable or not.
 */
counts: Counts, 
/**
 * ISO-8601 timestamp the check ran.
 */
checkedAt: string, 
/**
 * What the check was a claim about, for the sweep to compare against.
 */
basis: HealthCheckBasis, };
