// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a mod says it is licensed under.
 *
 * The name alone, which every mod's config already carries. A license's text
 * reaches disk for neither format and costs one archive mount, so it is read
 * where a reader asks to see it rather than beside every card.
 */
export type ModLicense = { 
/**
 * An SPDX id, or the name a custom license gives itself.
 */
name: string, 
/**
 * Where the full terms are, for a license that points anywhere.
 */
url?: string | null, };
