// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of a repair over several mods, emitted per mod.
 *
 * Its own payload rather than [`HealthSweepProgress`] reused: the two run at
 * different moments and a surface drawing one must not be driven by the other.
 */
export type ModRepairProgress = { current: number, total: number, modId: string, };
