// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one mod of a timed pass cost.
 */
export type ModTiming = { 
/**
 * The slug, because a uuid is a name nobody can map back to a mod.
 */
slug: string, millis: bigint, 
/**
 * What the pass concluded, or why it could not.
 */
outcome: string, };
