// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a new object of a declared document starts.
 */
export type NewObject = { "type": "clone", 
/**
 * The object copied, `0x` and eight hex digits.
 */
source: string, } | { "type": "class", 
/**
 * The class, as a name or `0x` and eight hex digits.
 */
class: string, };
