// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an object edit does not apply, as `ltk_game_data` names it.
 */
export type ObjectSkip = "objectExists" | "sourceMissing" | "unknownClass" | "removalUnmatched" | "unknown";
