// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewObject } from "./NewObject";

/**
 * An object edit of a declared document. ADR-0049.
 */
export type ObjectEdit = { "kind": "create", name: string, origin: NewObject, } | { "kind": "remove", entry: string, } | { "kind": "restore", entry: string, };
