// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a declaration creates an object or removes one.
 */
export type ObjectChange = "created" | "removed";
