// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An opened folder as the frontend lists it, whether or not it is still on disk.
 */
export type OpenedProjectFolder = { 
/**
 * The id the project's route names it by.
 */
id: string, path: string, displayName: string, 
/**
 * Whether the folder or its config is gone.
 */
missing: boolean, lastOpened: string | null, };
