// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the session was started for, without the paths a workshop one carries.
 */
export type OriginKind = "library" | "workshop";
