// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the DLL said after it attached.
 */
export type OverlayOutcome = "live" | "too-late" | "end-of-life" | "disabled" | "hook-failed" | "none";
