// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which way an overlay build failed, as the remedy a consumer picks between.
 *
 * Mirrors the categories of `ltk_overlay::Error`, which is not `Serialize`,
 * so records and IPC responses carry this while the detail stays in the
 * message.
 */
export type OverlayErrorCategory = "GAME_DIR" | "MOD_CONTENT" | "WAD_LIMIT" | "CORRUPT" | "BUG" | "FILE_IN_USE" | "OTHER";
