// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IgnoredEntry } from "./IgnoredEntry";

/**
 * Result of a successful pack operation.
 */
export type PackResult = { outputPath: string, fileName: string, format: string, 
/**
 * What the ignore rules left out, in the packer's traversal order.
 */
ignored: Array<IgnoredEntry>, };
