// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatcherPhase } from "./PatcherPhase";
import type { PatcherSession } from "./PatcherSession";

/**
 * Current status of the patcher.
 */
export type PatcherStatus = { 
/**
 * Whether the patcher is currently running.
 */
running: boolean, 
/**
 * Current phase of the patcher lifecycle.
 */
phase: PatcherPhase, 
/**
 * The session in flight. `null` while idle.
 */
session: PatcherSession | null, };
