// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionOrigin } from "./SessionOrigin";

/**
 * A patching session, from the moment it is asked for until the thread exits.
 */
export type PatcherSession = { 
/**
 * What the session was started for.
 */
origin: SessionOrigin, 
/**
 * The overlay root the session patches against, with a trailing separator.
 *
 * `None` until the build phase produces one.
 */
overlayPrefix: string | null, };
