// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinaryId } from "./BinaryId";

/**
 * Patcher identities
 */
export type PatcherBinaries = { dll?: BinaryId, host?: BinaryId, matchesBundle?: boolean, };
