// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revision } from "./Revision";

/**
 * One of a project's root text files, as the editor reads it.
 */
export type ProjectText = { 
/**
 * Absolute path of the file, whether or not one exists.
 */
path: string, 
/**
 * The file's text, null where no file exists or its bytes are not UTF-8.
 */
text: string | null, 
/**
 * Whether a file that exists decoded. A file that did not is read-only.
 */
readable: boolean, 
/**
 * What the file was when it was read, null where no file exists.
 */
revision: Revision | null, };
