// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A text file a project keeps at its root, beside `content/`.
 *
 * Naming the files rather than taking a path is what keeps a command that
 * writes into a project from being addressable at an arbitrary one.
 */
export type ProjectTextFile = "readme" | "license";
