// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a document takes no edit. "Where editing is allowed" in docs/ux/BIN_EDITOR.md.
 */
export type ReadOnly = "install" | "loose" | "patch" | "declarationsOff";
