// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Blending } from "./Blending";

/**
 * How a pass's fragments reach the target, from the first pass's own fields.
 */
export type RenderState = { blending: Blending, 
/**
 * `PREMULTIPLIED_ALPHA=1` among the macros.
 */
premultiplied: boolean, 
/**
 * `cullEnable` is off, so both faces draw.
 */
doubleSided: boolean, 
/**
 * The pass culls the winding the engine keeps by default, which an inverted hull does.
 */
inverted: boolean, depthWrite: boolean, depthTest: boolean, };
