// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a file was when it was read, so a save can tell it has not moved.
 *
 * Modification time and size rather than a hash of the bytes: one `stat`
 * answers it, and prose a person typed does not change back into the same
 * length within the same millisecond.
 */
export type Revision = { 
/**
 * Milliseconds since the Unix epoch, or 0 where the platform has no time.
 */
modifiedMs: bigint, size: bigint, };
