// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a rule speaks about a project, and what it waits for if not.
 *
 * A check about a change the installed game has not taken still runs, because
 * a modder wants to see what is coming. What it does not do is claim the mod
 * is broken today: the panel draws those findings muted and leaves them out
 * of the count in the project bar, and this is what tells it which they are.
 *
 * A rule that compares the mod against the installed game and finds no install
 * to compare with reports the same way, and reports nothing at all. A rule that
 * said nothing without saying why would read as a rule that found nothing.
 */
export type RuleState = { "kind": "active" } | { "kind": "dormant", 
/**
 * A few words a control can hold, such as `Patch 16.17`.
 */
waiting: string, 
/**
 * One sentence a reader who has not met this check can act on.
 */
reason: string, 
/**
 * The values behind `reason`, for a reader who wants them.
 */
detail: string | null, };
