// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The status the scan reported, as `WadScanFailedDialog` classifies it.
 *
 * Carried on the [`Incident`] so a consumer can tell one rejection from
 * another without reading [`Verdict::cause`] as prose.
 */
export type ScanStatus = "skinhack" | "missing-bin" | "corrupt" | "out-of-memory" | "base-skin" | "unknown";
