// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which scan the DLL ran, as it decided from the flags and the command line.
 */
export type ScanMode = "eager" | "lazy";
