// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";
import type { InjectionStage } from "./InjectionStage";

/**
 * A session that failed before any game ran.
 */
export type SessionFailure = { "build": { kind: ErrorKind, message: string, } } | { "injection": { stage: InjectionStage, message: string, } };
