// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a patching session was started for, and what it covers.
 */
export type SessionOrigin = { "kind": "library" } | { "kind": "workshop", 
/**
 * Absolute paths to the project directories under test.
 */
projects: Array<string>, };
