// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccentColor } from "./AccentColor";
import type { AuthorProfile } from "./AuthorProfile";
import type { LaunchMode } from "./LaunchMode";
import type { Theme } from "./Theme";
import type { WadBlocklistEntry } from "./WadBlocklistEntry";

/**
 * Application settings: UI/shell preferences plus the flattened core
 * [`Config`]. The flatten keeps `settings.json` a single flat document, so
 * the split is invisible to both the file on disk and the frontend.
 */
export type Settings = { firstRunComplete: boolean, 
/**
 * Application theme (system, dark, or light).
 */
theme: Theme, 
/**
 * Accent color configuration.
 */
accentColor: AccentColor, 
/**
 * Optional backdrop image path for glassmorphism effect.
 */
backdropImage: string | null, 
/**
 * Backdrop blur amount in pixels (default: 40).
 */
backdropBlur: number | null, 
/**
 * Library view mode ("grid" or "list"). Defaults to "grid".
 */
libraryViewMode: string | null, 
/**
 * Whether to minimize to system tray instead of taskbar. Default: true.
 */
minimizeToTray: boolean, 
/**
 * Whether to start the application minimized to the system tray. Default: false.
 */
startInTray: boolean, 
/**
 * Whether to register the app to launch automatically on login. Default: false.
 */
autoRun: boolean, 
/**
 * When starting in tray, show the window if an update is available. Default: false.
 */
startInTrayUnlessUpdate: boolean, 
/**
 * Always start the patcher automatically on launch. Default: false.
 */
alwaysStartPatcher: boolean, 
/**
 * What the library's primary button does. Default: [`LaunchMode::Classic`],
 * so an install that predates the launcher keeps the button it had.
 */
launchMode: LaunchMode, 
/**
 * Whether the user has dismissed the migration banner.
 */
migrationDismissed: boolean, 
/**
 * Global hotkey accelerator for reloading mods (e.g. "Ctrl+Shift+R").
 */
reloadModsHotkey: string | null, 
/**
 * Global hotkey accelerator for killing League (e.g. "Ctrl+Shift+K").
 */
killLeagueHotkey: string | null, 
/**
 * Whether the kill-league hotkey should also stop the patcher. Default: true.
 */
killLeagueStopsPatcher: boolean, 
/**
 * Trusted domains for protocol installs. Downloads are only allowed from these domains.
 */
trustedDomains: Array<string>, 
/**
 * Whether the library file watcher is enabled. Default: false.
 */
watcherEnabled: boolean, 
/**
 * Whether a mod card shows its category pills.
 *
 * The tags, champions and maps a mod declares, plus whatever
 * categorization derived. Display only, and on by default, since the pills
 * are how a crowded grid stays readable. Filtering is unaffected either way.
 */
showModTags: boolean, 
/**
 * Whether a mod card shows its WAD footprint badge.
 *
 * Display only. The footprint is still analyzed and still feeds
 * `Config::auto_categorization_enabled`, so hiding the badge costs no
 * categories. Default: false, since the WAD count means nothing to most
 * people installing a skin.
 */
showWadFootprint: boolean, authorProfiles: Array<AuthorProfile>, defaultAuthorProfileId: string | null, 
/**
 * Whether the user has dismissed the HDD-performance warning. Once true,
 * we suppress the warning on subsequent patcher starts. Reset by toggling
 * the "show performance warnings" setting if/when we add one.
 */
hasSeenHddWarning: boolean, leaguePath: string | null, modStoragePath: string | null, 
/**
 * Directory where mod projects are stored (for Creator Workshop).
 */
workshopPath: string | null, 
/**
 * Whether to patch TFT game files (Map22.wad.client). Default: false.
 */
patchTft: boolean, 
/**
 * Whether to block mods from patching Scripts.wad.client. Default: true.
 */
blockScriptsWad: boolean, 
/**
 * Whether to run the linked-bin dependency check before starting the patcher. Default: true.
 */
linkedBinCheckEnabled: boolean, 
/**
 * Additional WAD files to exclude from overlay building.
 */
wadBlocklist: Array<WadBlocklistEntry>, 
/**
 * Run the injection host elevated (UAC). An elevated game can only be
 * injected by an equally elevated host, so this is required when League
 * runs as administrator. Off by default: when off, non-elevated users
 * avoid a UAC prompt on every patcher start. Auto-elevation still kicks in
 * when League is detected configured to run as admin, regardless of this
 * flag (see `commands::patcher::start_patcher_inner`).
 */
elevateInjector: boolean, 
/**
 * Whether to automatically categorize mods from their content (champions,
 * maps and content tags derived from the WAD/chunk footprint, surfaced as
 * "auto" suggestions and library filters). When off, only the categories
 * the user sets themselves are used. Default: true.
 */
autoCategorizationEnabled: boolean, 
/**
 * Whether to enforce the anti-skinhack scan while patching. When on
 * (default), a champion WAD that fails the scan aborts patching. When off,
 * the `CSLOL_HOOK_OPT_OUT_AH_V1` hook flag is set so failures are
 * downgraded to warnings and flagged mods load anyway. Default: true.
 */
enforceSkinhackScan: boolean, 
/**
 * Whether mods' string overrides are applied to every installed locale
 * instead of only the locale the League client is configured to use.
 * Default: false (current locale only).
 */
applyStringOverridesToAllLocales: boolean, 
/**
 * Raise the injection host's log level from `Info` to `Debug`. The host and
 * the injected DLL decide their own verbosity from this, so it is the only
 * way to get their diagnostics out of a release build - `RUST_LOG` only
 * affects the manager's own tracing. Read at patcher start, so a change
 * takes effect on the next start. Default: false.
 */
verbosePatcherLogging: boolean, 
/**
 * Whether to set the `FULL_WAD_SCAN` hook flag, which scans every archive
 * up front instead of the DLL's default of verifying each one as the game
 * loads it. The overlay makes lazy scanning crash-prone, so the DLL only
 * scans lazily when the game has crash reporting disabled, which is what
 * [`Self::disable_crash_reporting`] is for - with crash reporting on, the
 * up-front scan happens either way and this flag changes nothing.
 * Default: false.
 */
fullWadScan: boolean, 
/**
 * Whether to turn the League client's crash reporting off when the
 * patcher starts, by clearing `install.crash_reporting.enabled` in its
 * `LeagueClientSettings.yaml`.
 *
 * The DLL verifies archives as the game loads them only while crash
 * reporting is off, so leaving it on costs every session the up-front
 * scan of every archive. The client rewrites its settings when it exits,
 * which is why the patcher applies this at every start rather than once.
 * Default: true.
 */
disableCrashReporting: boolean, 
/**
 * Whether to hide the Riot Client's window once the game is up. Nobody
 * launching through the manager wants the launcher left sitting on their
 * desktop behind the game, so this is on by default.
 *
 * Hides to the tray; the client keeps running because the game needs it for
 * the whole session, and it stays hidden after the game exits. That last
 * part takes active work: the client un-hides *itself* on exit, through the
 * `showUxIfHidden` flag on Foundation's UX command bus, so
 * `hide_for_play_session` re-asserts the hide. Reversible from the tray
 * icon at any point. Default: true.
 */
hideRiotClientOnLaunch: boolean, 
/**
 * Whether to read League's own game log after a game ends, for the
 * verdict on a game that went wrong. Turns the reader off. An incident
 * still records the ending, the game's boundaries and what the DLL said,
 * and with this off the manager opens nothing under the League install.
 * Default: true.
 */
readGameLog: boolean, 
/**
 * How many incidents the app data directory keeps, under 1MB together.
 * The oldest goes first, and a dismissed one before an undismissed one
 * of the same age. Default: 50.
 */
keepIncidents: number, };
