// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdleEffect } from "./IdleEffect";
import type { MaterialPreview } from "./MaterialPreview";
import type { NamedAsset } from "./NamedAsset";
import type { SubmeshOverride } from "./SubmeshOverride";

/**
 * A skin, as a viewport draws it.
 *
 * A submesh picks what it draws with in the engine's order: its override's `Material`,
 * else its override's `texture`, else the skin's `Material`, else the skin's `texture`.
 * Section 1.3 of docs/research/static-material-studio-rendering.md.
 */
export type SkinModel = { 
/**
 * The `.skn`, `skinMeshProperties.simpleSkin`.
 */
mesh: NamedAsset | null, 
/**
 * The `.skl`, `skinMeshProperties.skeleton`.
 */
skeleton: NamedAsset | null, 
/**
 * The texture a submesh draws with where no override names its own.
 */
texture: NamedAsset | null, 
/**
 * The `Material` a submesh draws with where no override names its own.
 */
material: MaterialPreview | null, 
/**
 * The submeshes a `materialOverride` gives a texture or a material of their own.
 */
overrides: Array<SubmeshOverride>, 
/**
 * The submeshes `initialSubmeshToHide` names, which the character starts without.
 */
hidden: Array<string>, 
/**
 * `skinScale`, which the character is drawn at.
 */
scale: number, 
/**
 * `skinAnimationProperties.animationGraphData`, `0x` and eight hex digits.
 */
animationGraph: string | null, 
/**
 * `idleParticlesEffects`, in the order the skin lists them.
 */
idleEffects: Array<IdleEffect>, };
