// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An archive the lazy scan skipped, with the DLL's reason.
 */
export type SkippedArchive = { wad: string, why: string, };
