// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialPreview } from "./MaterialPreview";
import type { NamedAsset } from "./NamedAsset";

/**
 * One submesh a material override gives its own texture or material.
 */
export type SubmeshOverride = { 
/**
 * The submesh's name as the `.skn` spells it.
 */
submesh: string, 
/**
 * The override's `texture`, which the submesh draws with in place of the skin's own.
 */
texture: NamedAsset | null, 
/**
 * The override's `Material`, which wins over every texture.
 */
material: MaterialPreview | null, };
