// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mod, or a workshop project, that the evidence implicates.
 */
export type Suspect = { modId: string | null, projectPath: string | null, displayName: string, 
/**
 * `writes Aatrox.wad.client, which holds the path`
 *
 * The reason is the whole claim. How direct the link is reads out of what
 * it says - holding the path is not the same sentence as having been
 * redirected - so no separate word grades it.
 */
because: string, };
