// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Because } from "./Because";

/**
 * A mod, or a workshop project, that the evidence implicates.
 */
export type Suspect = { modId: string | null, projectPath: string | null, displayName: string, 
/**
 * `writes Aatrox.wad.client, which holds the path`
 *
 * The reason is the whole claim. How direct the link is reads out of what
 * it says - holding the path is not the same sentence as having been
 * redirected - so no separate word grades it.
 */
because: string, 
/**
 * The same claim as a word, for a reader that groups rather than reads.
 *
 * [`Suspect::because`] names the archives, so it is prose and one of a kind
 * per suspect. This is what a count is taken over. Defaulted, because an
 * incident stored before it existed carries no reason.
 */
reason: Because, };
