// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";

/**
 * A mod, or a workshop project, that the evidence implicates.
 */
export type Suspect = { modId: string | null, projectPath: string | null, displayName: string, 
/**
 * `writes Aatrox.wad.client, which holds the path`
 */
because: string, confidence: Confidence, };
