// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The file format a texture arrives in.
 */
export type TextureContainer = "TEX" | "DDS";
