// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextureContainer } from "./TextureContainer";

/**
 * What a texture file declares about itself.
 */
export type TextureInfo = { width: number, height: number, container: TextureContainer, 
/**
 * The block format, where the container names one.
 *
 * `None` for a DDS, because `ltk_texture` keeps the header private.
 */
format: string | null, mipCount: number, 
/**
 * The size of the file itself, not of a decoded mipmap.
 */
sizeBytes: bigint, };
