// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";
import type { VerdictKind } from "./VerdictKind";

/**
 * What the manager concluded from one game.
 */
export type Verdict = { kind: VerdictKind, title: string, 
/**
 * One or two sentences under the title.
 */
cause: string, 
/**
 * The archive, the path's file name, or the step, where there is one.
 */
subject: string | null, 
/**
 * Absent for a verdict that states facts, where a confidence reads as a hedge.
 */
confidence: Confidence | null, 
/**
 * At most two, one sentence each.
 */
hints: Array<string>, };
