// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Consequence } from "./Consequence";
import type { VerdictKind } from "./VerdictKind";

/**
 * What the manager concluded from one game.
 */
export type Verdict = { kind: VerdictKind, 
/**
 * The title as it reads, from [`VerdictKind::title`] unless this verdict
 * named its own.
 *
 * Derived on the way in, so a stored incident cannot keep a title this
 * build has stopped using. Renaming a kind renames its history with it.
 */
title: string, 
/**
 * A title for something the kind's own does not cover, and `None` for
 * every verdict the predefined set already describes.
 */
titleOverride: string | null, 
/**
 * One or two sentences under the title.
 */
cause: string, 
/**
 * The archive, the path's file name, or the step, where there is one.
 */
subject: string | null, 
/**
 * What the game lost, which [`VerdictKind`] alone decides.
 *
 * Written out for a reader, and never read back. [`Self::kind`] decides it,
 * so reading it from a file would only let a stale one disagree.
 */
consequence: Consequence, 
/**
 * At most two, one sentence each.
 */
hints: Array<string>, };
