// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A sampler's address mode, `addressU` and `addressV` on the wire.
 */
export type Wrap = "repeat" | "clamp" | "mirror" | "border";
