import { useQuery } from "@tanstack/react-query";

import { settingsKeys } from "./keys";

export interface LicenseText {
  id: string;
  name: string;
  text: string;
}

export interface ThirdPartyCrate {
  name: string;
  version: string;
  url?: string;
  /** Indices into the manifest's `texts` array. */
  licenses: number[];
}

export interface ThirdPartyLicensesManifest {
  texts: LicenseText[];
  crates: ThirdPartyCrate[];
}

// Generated by `pnpm generate:licenses` (cargo-about), served as a static asset
async function fetchThirdPartyLicenses(): Promise<ThirdPartyLicensesManifest> {
  const response = await fetch("/third-party-licenses.json");
  if (!response.ok) {
    throw new Error(`Failed to load license manifest (${response.status})`);
  }
  return (await response.json()) as ThirdPartyLicensesManifest;
}

export function useThirdPartyLicenses(enabled: boolean) {
  return useQuery<ThirdPartyLicensesManifest, Error>({
    queryKey: settingsKeys.thirdPartyLicenses(),
    queryFn: fetchThirdPartyLicenses,
    staleTime: Infinity,
    enabled,
  });
}
