// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import type { AppErrorResponse, DeepLinkRequest, InstalledMod_Serialize } from "../bindings";

/** Commands */
export const commands = {
	/**
	 *  Install a mod from a deep-link protocol URL.
	 * 
	 *  Downloads the file to a temp directory, validates it, then installs
	 *  using the existing mod library pipeline.
	 */
	deepLinkInstallMod: (url: string, name: string | null, author: string | null, source: string | null) => __TAURI_INVOKE<({ ok: true; value: InstalledMod_Serialize }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:links|deep_link_install_mod", { url, name, author, source }),
	/**
	 *  Take the deep link that arrived before the frontend could listen for it.
	 * 
	 *  A URL handed to a cold start reaches the backend while the window's script is
	 *  still loading, so the event carrying it would reach nobody. The frontend asks
	 *  once, as its listener comes up, and the answer is `None` from then on.
	 */
	takePendingDeepLink: () => __TAURI_INVOKE<({ ok: true; value: DeepLinkRequest | null }) & { error?: never } | ({ ok: false; error: AppErrorResponse }) & { value?: never }>("plugin:links|take_pending_deep_link"),
};

/* Constants */
export const commandNames = {"deepLinkInstallMod":"plugin:links|deep_link_install_mod","takePendingDeepLink":"plugin:links|take_pending_deep_link"} as const;
